import os
path = '/home/mettaclaw/artifacts/content_pipeline_v3_final.html'
f = open(path, 'w')
f.write('<!DOCTYPE html>\n<html><head><meta charset="utf-8"><title>OmegaClaw Launch Pipeline V3</title>\n')
f.write('<style>\n')
f.write('body{background:#111;color:#e0e0e0;font-family:Georgia,serif;max-width:900px;margin:0 auto;padding:20px;line-height:1.7}\n')
f.write('h1{color:#0ff;border-bottom:2px solid #0ff;padding-bottom:10px}\n')
f.write('h2{color:#0af;margin-top:30px;border-bottom:1px solid #333;padding-bottom:5px}\n')
f.write('h3{color:#c792ea}\n')
f.write('.day{border-left:3px solid #0af;padding:10px 15px;margin:15px 0;background:#1a1a2e}\n')
f.write('.tweet{background:#0a2a0a;border-left:3px solid #0f0;padding:10px;margin:6px 0;border-radius:4px}\n')
f.write('.article{background:#2a1a00;border-left:3px solid #fa0;padding:10px;margin:6px 0;border-radius:4px}\n')
f.write('.video{background:#1a0a2a;border-left:3px solid #c0f;padding:10px;margin:6px 0;border-radius:4px}\n')
f.write('.space{background:#0a1a2a;border-left:3px solid #0af;padding:10px;margin:6px 0;border-radius:4px}\n')
f.write('.legend{display:flex;gap:15px;margin:15px 0;flex-wrap:wrap}\n')
f.write('.legend span{padding:4px 10px;border-radius:4px;font-size:0.9em}\n')
f.write('</style></head><body>\n')
f.write('<h1>OmegaClaw: 3-Week Launch Content Pipeline V3</h1>\n')
f.write('<p>21 days. 9 articles. 63 tweets. 3 videos. 3 X-Spaces. Color-coded by content type.</p>\n')
f.write('<div class="legend"><span class="tweet">Tweet</span><span class="article">Article</span><span class="video">Video</span><span class="space">X-Space</span></div>\n')
f.close()
print('header written', os.path.getsize(path), 'bytes')
